### ISSUE TITLE
Integrate "get involved" form into Hivenyc.org community page

### ISSUE THREAD

**Issue by jvallera** [MozillaHive/HiveNYC.org#1]
get involved form: https://docs.google.com/forms/d/1MS3ERefQCvO3jPOXTJvOb1eYgHdzsCcV6p_-cI6VqTY/viewform
Looking at Maker Magazine pledge form as an example: http://makezine.com/day-of-making/#signup
We want the get involved form to be accessible through a pop-up window via the community page on Hivenyc.org. Here is the community page: http://hivenyc.org/?page_id=8670&preview=true

**Comment by ldecoursy** [comment]
Hi @jvallera Can we close this ticket? Going to have the team start using the  https://github.com/MozillaFoundation/Mozilla-Learning repo moving forward - just want to make sure we move things that are still in play.
